name: Run RSpec Tests

on:
  pull_request:
    types: [review_requested, ready_for_review, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.2'

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Run RSpec tests
      run: bundle exec rspec
